---
title: "belg: Boltzmann Entropy of a Landscape Gradient"
author: "Jakub Nowosad"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(ggplot2)
library(rasterVis)
theme_clean = function (base_size = 12, base_family = ""){
  theme_grey(base_size = base_size, base_family = base_family) %+replace% 
    theme(axis.line = element_blank(), axis.text.x = element_blank(), 
      axis.text.y = element_blank(), axis.ticks = element_blank(), 
      axis.title.x = element_blank(), axis.title.y = element_blank(), 
      axis.ticks.length = grid::unit(0, "lines"), legend.position = "none", 
      panel.background = element_blank(), panel.border = element_blank(), 
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
      panel.spacing = grid::unit(0, "lines"), plot.background = element_blank(), 
      strip.background = element_rect(colour = "#ffffff", 
        fill = "#eeeeee"))
}
theme_set(theme_clean())
```

```{r}
library(belg)
library(raster)
ver_1 = raster(matrix(c(1, 3, 3, 4), ncol = 2))
ver_2 = raster(matrix(c(1, 3, 3, NA), ncol = 2))
ver_3 = raster(matrix(c(1, 3, NA, NA), ncol = 2))
ver_4 = raster(matrix(c(1, NA, NA, NA), ncol = 2))
ver_5 = raster(matrix(c(NA, NA, NA, NA), ncol = 2))
```

```{r, echo = FALSE}
gplot(ver_1) + 
  geom_tile(aes(fill = as.factor(value)), color = "black", size = 2) +
  geom_text(aes(label = value), size = 6) +
  scale_fill_manual(values = c("#fc8d59", "#ffffbf", "#91bfdb"))
```

```{r}
log10(24)
get_boltzmann(ver_1)
```

# Support for data with missing values

```{r, echo = FALSE}
gplot(ver_2) + 
  geom_tile(aes(fill = as.factor(value)), color = "black", size = 2) +
  geom_text(aes(label = c(1, 3, 3, "NA")), size = 6) +
  scale_fill_manual(values = c("#fc8d59", "#ffffbf", "#91bfdb"))
```

```{r}
log10(3)
get_boltzmann(ver_2)
```

```{r, echo = FALSE}
gplot(ver_3) + 
  geom_tile(aes(fill = as.factor(value)), color = "black", size = 2) +
  geom_text(aes(label = c(1, "NA", 3, "NA")), size = 6) +
  scale_fill_manual(values = c("#fc8d59", "#ffffbf", "#91bfdb"))
```

```{r}
log10(2)
get_boltzmann(ver_3)
```

```{r, echo = FALSE}
gplot(ver_4) + 
  geom_tile(aes(fill = as.factor(value)), color = "black", size = 2) +
  geom_text(aes(label = c(1, "NA", "NA", "NA")), size = 6) +
  scale_fill_manual(values = c("#fc8d59", "#ffffbf", "#91bfdb"))
```

```{r}
log10(1)
get_boltzmann(ver_4)
```

```{r, echo = FALSE}
gplot(ver_5) + 
  geom_tile(fill = "grey50", color = "black", size = 2) +
  geom_text(aes(label = c("NA", "NA", "NA", "NA")), size = 6) +
  scale_fill_manual(values = c("#fc8d59", "#ffffbf", "#91bfdb"))
```

```{r}
0
get_boltzmann(ver_5)
```
