# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_boltzmann <- function(raster, base = "log", relative = FALSE) {
    .Call('_belg_get_boltzmann', PACKAGE = 'belg', raster, base, relative)
}

