# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_boltzmann_default <- function(x, base, relative) {
    .Call('_belg_get_boltzmann_default', PACKAGE = 'belg', x, base, relative)
}

find_na <- function(sub_x) {
    .Call('_belg_find_na', PACKAGE = 'belg', sub_x)
}

count_permutations <- function(number) {
    .Call('_belg_count_permutations', PACKAGE = 'belg', number)
}

