# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_boltzmann_default <- function(x, base, relative) {
    .Call('_belg_get_boltzmann_default', PACKAGE = 'belg', x, base, relative)
}

get_boltzmann_aggregation <- function(x, base, relative) {
    .Call('_belg_get_boltzmann_aggregation', PACKAGE = 'belg', x, base, relative)
}

not_na_prop <- function(x) {
    .Call('_belg_not_na_prop', PACKAGE = 'belg', x)
}

