on:
  push:
    branches: master
  pull_request:
    branches:
      - master

name: pkgdown-and-test-coverage

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-3.6-${{ hashFiles('depends.Rds') }}
          restore-keys: macOS-r-3.6-

      - name: Brew
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install udunits
          rm '/usr/local/bin/gfortran'
          brew install gdal
          brew install sqlite3
      - name: Install dependencies
        run: |
          install.packages("remotes")
          # install.packages("sf", configure.args = "--with-proj-lib=/usr/local/lib/")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
          # remotes::install_github("r-lib/pkgdown#1276")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --global user.name ${{secrets.GH_USER}}
          git config --global user.email ${{secrets.GH_EMAIL}}
          Rscript -e "pkgdown::deploy_to_branch(new_process = FALSE)"
